### ISSUE TITLE
bpmn js seed does not contain some demo functionality

### ISSUE THREAD

**Issue by alperenbelgic** [bpmn-io/bpmn-js-seed#1]
Hello,
First of all, thank you for these great tools.
I downloaded the seed project but I cannot see some features like "reset zoom" and "open diagram from file system". Is it expected behavior? If I built the project, would I see those features? Or should I implement them myself?
Thank you.

**Comment by nikku** [comment]
You should implement them yourself.

bpmn-js is a toolkit and the demo only shows some of the things that are possible.

Have a look through [our examples](https://github.com/bpmn-io/bpmn-js-examples) to learn more.

**Comment by alperenbelgic** [comment]
Thanks.
